<?php
$sql_insert = "INSERT INTO ".$wpdb->prefix."spiderfc_theme(title, paramsname, paramsdescrip, paramsvalue, theme_default, theme_id) 
					VALUES
( 'Simple blue', 'startWithMonday', '', '1', 1, 1),
( 'Simple blue', 'dateFormat', '', '%d-%m-%y %t', 1, 1),
( 'Simple blue', 'dateFormatShort', '', '%t', 1, 1),
( 'Simple blue', 'time', '', '0', 1, 1),
( 'Simple blue', 'appMaxWidth', '', '600', 1, 1),
( 'Simple blue', 'appMaxHeight', '', '550', 1, 1),
( 'Simple blue', 'appMinWidth', '', '360', 1, 1),
( 'Simple blue', 'appMinHeight', '', '420', 1, 1),
( 'Simple blue', 'startViewSize', '', 'viewSizeMax', 1, 1),
( 'Simple blue', 'startViewState', '', 'viewStateDays', 1, 1),
( 'Simple blue', 'bgColors', '', 'FFFFFF;FFFFFF', 1, 1),
( 'Simple blue', 'bgCornerRadius', '', '15', 1, 1),
( 'Simple blue', 'strokeColor', '', '808080', 1, 1),
( 'Simple blue', 'headerHeight', '', '100', 1, 1),
( 'Simple blue', 'headerPadding', '', '20', 1, 1),
( 'Simple blue', 'headerBgColors', '', 'AADCFF;9ECFF2', 1, 1),
( 'Simple blue', 'headerBgStrokeColor', '', '203540', 1, 1),
( 'Simple blue', 'headerContentColor', '', 'FFFFFF', 1, 1),
( 'Simple blue', 'headerContentStrokeColor', '', '404040', 1, 1),
( 'Simple blue', 'headerFontSize', '', '40', 1, 1),
( 'Simple blue', 'daysNamesColor', '', '808080', 1, 1),
( 'Simple blue', 'daysNamesFontSize', '', '24', 1, 1),
( 'Simple blue', 'datesBgColors', '', 'F3F3F3;E6E6E6', 1, 1),
( 'Simple blue', 'priority0Color', '', '4D9AFF', 1, 1),
( 'Simple blue', 'priority1Color', '', '55FF00', 1, 1),
( 'Simple blue', 'priority2Color', '', 'FFD400', 1, 1),
( 'Simple blue', 'priority3Color', '', 'FF0000', 1, 1),
( 'Simple blue', 'dateFontSize', '', '40', 1, 1),
( 'Simple blue', 'dateColor', '', '404040', 1, 1),
( 'Simple blue', 'dateStrokeColor', '', '404040', 1, 1),
( 'Simple blue', 'showDateEventsCount', '', '1', 1, 1),
( 'Simple blue', 'dateEventsCountFontSize', '', '12', 1, 1),
( 'Simple blue', 'dateEventsCountColor', '', '606060', 1, 1),
( 'Simple blue', 'eventsListHeaderHeight', '', '50', 1, 1),
( 'Simple blue', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 1, 1),
( 'Simple blue', 'eventsListHeaderColor', '', '404040', 1, 1),
( 'Simple blue', 'eventsListHeaderFontSize', '', '20', 1, 1),
( 'Simple blue', 'eventHeaderHeight', '', '40', 1, 1),
( 'Simple blue', 'eventHeaderFontSize', '', '20', 1, 1),
( 'Simple blue', 'eventHeaderColor', '', '000000', 1, 1),
( 'Simple blue', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 1, 1),
( 'Simple blue', 'eventContentDatesFontSize', '', '18', 1, 1),
( 'Simple blue', 'eventContentDatesColor', '', '808080', 1, 1),
( 'Simple blue', 'eventContentDescriptionFontSize', '', '16', 1, 1),
( 'Simple blue', 'eventContentDescriptionColor', '', '404040', 1, 1),
( 'Simple blue', 'footerHeight', '', '30', 1, 1),
( 'Simple blue', 'footerColor', '', '808080', 1, 1),
( 'Simple blue', 'mediaDefaultAutoplay', '', '1', 1, 1),
( 'Simple blue', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 1, 1),
( 'Simple blue', 'mediaShowDuration', '', '5', 1, 1),
( 'Simple blue', 'videoDefaultVolume', '', '80', 1, 1),
( 'Simple blue', 'videoAutoplay', '', '0', 1, 1),
( 'Simple blue', 'mediaBgColor', '', '000000', 1, 1),
( 'Simple blue', 'mediaCtrlsBgColor', '', '363D40', 1, 1),
( 'Simple blue', 'mediaCtrlsBgAlpha', '', '80', 1, 1),
( 'Simple blue', 'mediaCtrlsColor', '', 'D3DADE', 1, 1),
( 'Simple blue', 'mediaCtrlsAlpha', '', '100', 1, 1),



('Black', 'startWithMonday', '', '1', 0, 2),
('Black', 'dateFormat', '', '%d-%m-%y %t', 0, 2),
('Black', 'dateFormatShort', '', '%t', 0, 2),
('Black', 'time', '', '0', 0, 2),
('Black', 'appMaxWidth', '', '600', 0, 2),
('Black', 'appMaxHeight', '', '550', 0, 2),
('Black', 'appMinWidth', '', '360', 0, 2),
('Black', 'appMinHeight', '', '420', 0, 2),
('Black', 'startViewSize', '', 'viewSizeMax', 0, 2),
('Black', 'startViewState', '', 'viewStateDays', 0, 2),
('Black', 'bgColors', '', '0A0A0A;101010', 0, 2),
('Black', 'bgCornerRadius', '', '12', 0, 2),
('Black', 'strokeColor', '', '08BDF4', 0, 2),
('Black', 'headerHeight', '', '100', 0, 2),
('Black', 'headerPadding', '', '14', 0, 2),
('Black', 'headerBgColors', '', '0A0A0A;101010', 0, 2),
('Black', 'headerBgStrokeColor', '', '08BDF4', 0, 2),
('Black', 'headerContentColor', '', 'FFFFFF', 0, 2),
('Black', 'headerContentStrokeColor', '', '404040', 0, 2),
('Black', 'headerFontSize', '', '40', 0, 2),
('Black', 'daysNamesColor', '', 'C7C7C7', 0, 2),
('Black', 'daysNamesFontSize', '', '20', 0, 2),
('Black', 'datesBgColors', '', '050507;050507', 0, 2),
('Black', 'priority0Color', '', 'A9FF9C', 0, 2),
('Black', 'priority1Color', '', '61FF7B', 0, 2),
('Black', 'priority2Color', '', '0A0A0A', 0, 2),
('Black', 'priority3Color', '', 'FF0000', 0, 2),
('Black', 'dateFontSize', '', '40', 0, 2),
('Black', 'dateColor', '', 'A6A6A6', 0, 2),
('Black', 'dateStrokeColor', '', 'D90000', 0, 2),
('Black', 'showDateEventsCount', '', '1', 0, 2),
('Black', 'dateEventsCountFontSize', '', '12', 0, 2),
('Black', 'dateEventsCountColor', '', '08BDF4', 0, 2),
('Black', 'eventsListHeaderHeight', '', '50', 0, 2),
('Black', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 2),
('Black', 'eventsListHeaderColor', '', '404040', 0, 2),
('Black', 'eventsListHeaderFontSize', '', '20', 0, 2),
('Black', 'eventHeaderHeight', '', '40', 0, 2),
('Black', 'eventHeaderFontSize', '', '20', 0, 2),
('Black', 'eventHeaderColor', '', 'FFFFFF', 0, 2),
('Black', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 2),
('Black', 'eventContentDatesFontSize', '', '18', 0, 2),
('Black', 'eventContentDatesColor', '', '808080', 0, 2),
('Black', 'eventContentDescriptionFontSize', '', '16', 0, 2),
('Black', 'eventContentDescriptionColor', '', '404040', 0, 2),
('Black', 'footerHeight', '', '30', 0, 2),
('Black', 'footerColor', '', '808080', 0, 2),
('Black', 'mediaDefaultAutoplay', '', '1', 0, 2),
('Black', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 2),
('Black', 'mediaShowDuration', '', '5', 0, 2),
('Black', 'videoDefaultVolume', '', '80', 0, 2),
('Black', 'videoAutoplay', '', '0', 0, 2),
('Black', 'mediaBgColor', '', '000000', 0, 2),
('Black', 'mediaCtrlsBgColor', '', '363D40', 0, 2),
('Black', 'mediaCtrlsBgAlpha', '', '80', 0, 2),
('Black', 'mediaCtrlsColor', '', 'D3DADE', 0, 2),
('Black', 'mediaCtrlsAlpha', '', '100', 0, 2),



( 'Simple grey ', 'startWithMonday', '', '1', 0, 3),
( 'Simple grey ', 'dateFormat', '', '%d-%m-%y %t', 0, 3),
( 'Simple grey ', 'dateFormatShort', '', '%t', 0, 3),
( 'Simple grey ', 'time', '', '1', 0, 3),
( 'Simple grey ', 'appMaxWidth', '', '600', 0, 3),
( 'Simple grey ', 'appMaxHeight', '', '550', 0, 3),
( 'Simple grey ', 'appMinWidth', '', '340', 0, 3),
( 'Simple grey ', 'appMinHeight', '', '400', 0, 3),
( 'Simple grey ', 'startViewSize', '', 'viewSizeMax', 0, 3),
( 'Simple grey ', 'startViewState', '', 'viewStateDays', 0, 3),
( 'Simple grey ', 'bgColors', '', '2D2D2D;222222', 0, 3),
( 'Simple grey ', 'bgCornerRadius', '', '0', 0, 3),
( 'Simple grey ', 'strokeColor', '', '000000', 0, 3),
( 'Simple grey ', 'headerHeight', '', '100', 0, 3),
( 'Simple grey ', 'headerPadding', '', '2', 0, 3),
( 'Simple grey ', 'headerBgColors', '', '2D2D2D;222222', 0, 3),
( 'Simple grey ', 'headerBgStrokeColor', '', '203540', 0, 3),
( 'Simple grey ', 'headerContentColor', '', 'FFFFFF', 0, 3),
( 'Simple grey ', 'headerContentStrokeColor', '', '404040', 0, 3),
( 'Simple grey ', 'headerFontSize', '', '40', 0, 3),
( 'Simple grey ', 'daysNamesColor', '', 'FFFFFF', 0, 3),
( 'Simple grey ', 'daysNamesFontSize', '', '20', 0, 3),
( 'Simple grey ', 'datesBgColors', '', 'E1E1E1;F5F5F5', 0, 3),
( 'Simple grey ', 'priority0Color', '', '55FF00', 0, 3),
( 'Simple grey ', 'priority1Color', '', '55FF00', 0, 3),
( 'Simple grey ', 'priority2Color', '', 'FFD400', 0, 3),
( 'Simple grey ', 'priority3Color', '', 'FF0000', 0, 3),
( 'Simple grey ', 'dateFontSize', '', '40', 0, 3),
( 'Simple grey ', 'dateColor', '', '404040', 0, 3),
( 'Simple grey ', 'dateStrokeColor', '', '404040', 0, 3),
( 'Simple grey ', 'showDateEventsCount', '', '1', 0, 3),
( 'Simple grey ', 'dateEventsCountFontSize', '', '12', 0, 3),
( 'Simple grey ', 'dateEventsCountColor', '', '606060', 0, 3),
( 'Simple grey ', 'eventsListHeaderHeight', '', '50', 0, 3),
( 'Simple grey ', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 3),
( 'Simple grey ', 'eventsListHeaderColor', '', '404040', 0, 3),
( 'Simple grey ', 'eventsListHeaderFontSize', '', '20', 0, 3),
( 'Simple grey ', 'eventHeaderHeight', '', '40', 0, 3),
( 'Simple grey ', 'eventHeaderFontSize', '', '20', 0, 3),
( 'Simple grey ', 'eventHeaderColor', '', '000000', 0, 3),
( 'Simple grey ', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 3),
( 'Simple grey ', 'eventContentDatesFontSize', '', '18', 0, 3),
( 'Simple grey ', 'eventContentDatesColor', '', '808080', 0, 3),
( 'Simple grey ', 'eventContentDescriptionFontSize', '', '16', 0, 3),
( 'Simple grey ', 'eventContentDescriptionColor', '', '404040', 0, 3),
( 'Simple grey ', 'footerHeight', '', '30', 0, 3),
( 'Simple grey ', 'footerColor', '', '808080', 0, 3),
( 'Simple grey ', 'mediaDefaultAutoplay', '', '1', 0, 3),
( 'Simple grey ', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 3),
( 'Simple grey ', 'mediaShowDuration', '', '5', 0, 3),
( 'Simple grey ', 'videoDefaultVolume', '', '80', 0, 3),
( 'Simple grey ', 'videoAutoplay', '', '0', 0, 3),
( 'Simple grey ', 'mediaBgColor', '', '000000', 0, 3),
( 'Simple grey ', 'mediaCtrlsBgColor', '', '363D40', 0, 3),
( 'Simple grey ', 'mediaCtrlsBgAlpha', '', '80', 0, 3),
( 'Simple grey ', 'mediaCtrlsColor', '', 'D3DADE', 0, 3),
( 'Simple grey ', 'mediaCtrlsAlpha', '', '100', 0, 3),




( 'Light brown', 'startWithMonday', '', '1', 0, 4),
( 'Light brown', 'dateFormat', '', '%d-%m-%y %t', 0, 4),
( 'Light brown', 'dateFormatShort', '', '%t', 0, 4),
( 'Light brown', 'time', '', '0', 0, 4),
( 'Light brown', 'appMaxWidth', '', '600', 0, 4),
( 'Light brown', 'appMaxHeight', '', '550', 0, 4),
( 'Light brown', 'appMinWidth', '', '360', 0, 4),
( 'Light brown', 'appMinHeight', '', '420', 0, 4),
( 'Light brown', 'startViewSize', '', 'viewSizeMax', 0, 4),
( 'Light brown', 'startViewState', '', 'viewStateDays', 0, 4),
( 'Light brown', 'bgColors', '', '523F30;8F6E54', 0, 4),
( 'Light brown', 'bgCornerRadius', '', '15', 0, 4),
( 'Light brown', 'strokeColor', '', '808080', 0, 4),
( 'Light brown', 'headerHeight', '', '100', 0, 4),
( 'Light brown', 'headerPadding', '', '20', 0, 4),
( 'Light brown', 'headerBgColors', '', 'BE7530;E7C892', 0, 4),
( 'Light brown', 'headerBgStrokeColor', '', '203540', 0, 4),
( 'Light brown', 'headerContentColor', '', 'FFFFFF', 0, 4),
( 'Light brown', 'headerContentStrokeColor', '', '404040', 0, 4),
( 'Light brown', 'headerFontSize', '', '40', 0, 4),
( 'Light brown', 'daysNamesColor', '', 'FFFFFF', 0, 4),
( 'Light brown', 'daysNamesFontSize', '', '20', 0, 4),
( 'Light brown', 'datesBgColors', '', '7E5F43;1EBD68', 0, 4),
( 'Light brown', 'priority0Color', '', 'FFBFE1', 0, 4),
( 'Light brown', 'priority1Color', '', '55FF00', 0, 4),
( 'Light brown', 'priority2Color', '', 'FFD400', 0, 4),
( 'Light brown', 'priority3Color', '', 'FF0000', 0, 4),
( 'Light brown', 'dateFontSize', '', '40', 0, 4),
( 'Light brown', 'dateColor', '', 'EB1F1F', 0, 4),
( 'Light brown', 'dateStrokeColor', '', 'E786B6', 0, 4),
( 'Light brown', 'showDateEventsCount', '', '1', 0, 4),
( 'Light brown', 'dateEventsCountFontSize', '', '12', 0, 4),
( 'Light brown', 'dateEventsCountColor', '', '606060', 0, 4),
( 'Light brown', 'eventsListHeaderHeight', '', '50', 0, 4),
( 'Light brown', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 4),
( 'Light brown', 'eventsListHeaderColor', '', '404040', 0, 4),
( 'Light brown', 'eventsListHeaderFontSize', '', '20', 0, 4),
( 'Light brown', 'eventHeaderHeight', '', '40', 0, 4),
( 'Light brown', 'eventHeaderFontSize', '', '20', 0, 4),
( 'Light brown', 'eventHeaderColor', '', '000000', 0, 4),
( 'Light brown', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 4),
( 'Light brown', 'eventContentDatesFontSize', '', '18', 0, 4),
( 'Light brown', 'eventContentDatesColor', '', '808080', 0, 4),
( 'Light brown', 'eventContentDescriptionFontSize', '', '16', 0, 4),
( 'Light brown', 'eventContentDescriptionColor', '', '404040', 0, 4),
( 'Light brown', 'footerHeight', '', '30', 0, 4),
( 'Light brown', 'footerColor', '', '808080', 0, 4),
( 'Light brown', 'mediaDefaultAutoplay', '', '1', 0, 4),
( 'Light brown', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 4),
( 'Light brown', 'mediaShowDuration', '', '5', 0, 4),
( 'Light brown', 'videoDefaultVolume', '', '80', 0, 4),
( 'Light brown', 'videoAutoplay', '', '0', 0, 4),
( 'Light brown', 'mediaBgColor', '', '000000', 0, 4),
( 'Light brown', 'mediaCtrlsBgColor', '', '363D40', 0, 4),
( 'Light brown', 'mediaCtrlsBgAlpha', '', '80', 0, 4),
( 'Light brown', 'mediaCtrlsColor', '', 'D3DADE', 0, 4),
( 'Light brown', 'mediaCtrlsAlpha', '', '100', 0, 4),




( 'Red blur', 'startWithMonday', '', '1', 0, 5),
( 'Red blur', 'dateFormat', '', '%d-%m-%y %t', 0, 5),
( 'Red blur', 'dateFormatShort', '', '%t', 0, 5),
( 'Red blur', 'time', '', '0', 0, 5),
( 'Red blur', 'appMaxWidth', '', '600', 0, 5),
( 'Red blur', 'appMaxHeight', '', '550', 0, 5),
( 'Red blur', 'appMinWidth', '', '360', 0, 5),
( 'Red blur', 'appMinHeight', '', '420', 0, 5),
( 'Red blur', 'startViewSize', '', 'viewSizeMax', 0, 5),
( 'Red blur', 'startViewState', '', 'viewStateDays', 0, 5),
( 'Red blur', 'bgColors', '', 'FFFFCD;C7C7A0', 0, 5),
( 'Red blur', 'bgCornerRadius', '', '6', 0, 5),
( 'Red blur', 'strokeColor', '', '000000', 0, 5),
( 'Red blur', 'headerHeight', '', '100', 0, 5),
( 'Red blur', 'headerPadding', '', '20', 0, 5),
( 'Red blur', 'headerBgColors', '', '9A0000;B5911B', 0, 5),
( 'Red blur', 'headerBgStrokeColor', '', '203540', 0, 5),
( 'Red blur', 'headerContentColor', '', 'FFFFFF', 0, 5),
( 'Red blur', 'headerContentStrokeColor', '', '404040', 0, 5),
( 'Red blur', 'headerFontSize', '', '36', 0, 5),
( 'Red blur', 'daysNamesColor', '', '808080', 0, 5),
( 'Red blur', 'daysNamesFontSize', '', '22', 0, 5),
( 'Red blur', 'datesBgColors', '', 'CECB96;DEDBA2', 0, 5),
( 'Red blur', 'priority0Color', '', '55FF00', 0, 5),
( 'Red blur', 'priority1Color', '', '55FF00', 0, 5),
( 'Red blur', 'priority2Color', '', 'FFD400', 0, 5),
( 'Red blur', 'priority3Color', '', 'FF0000', 0, 5),
( 'Red blur', 'dateFontSize', '', '33', 0, 5),
( 'Red blur', 'dateColor', '', '000000', 0, 5),
( 'Red blur', 'dateStrokeColor', '', '9A0000', 0, 5),
( 'Red blur', 'showDateEventsCount', '', '1', 0, 5),
( 'Red blur', 'dateEventsCountFontSize', '', '12', 0, 5),
( 'Red blur', 'dateEventsCountColor', '', '606060', 0, 5),
( 'Red blur', 'eventsListHeaderHeight', '', '50', 0, 5),
( 'Red blur', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 5),
( 'Red blur', 'eventsListHeaderColor', '', '404040', 0, 5),
( 'Red blur', 'eventsListHeaderFontSize', '', '20', 0, 5),
( 'Red blur', 'eventHeaderHeight', '', '40', 0, 5),
( 'Red blur', 'eventHeaderFontSize', '', '20', 0, 5),
( 'Red blur', 'eventHeaderColor', '', '000000', 0, 5),
( 'Red blur', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 5),
( 'Red blur', 'eventContentDatesFontSize', '', '18', 0, 5),
( 'Red blur', 'eventContentDatesColor', '', '808080', 0, 5),
( 'Red blur', 'eventContentDescriptionFontSize', '', '16', 0, 5),
( 'Red blur', 'eventContentDescriptionColor', '', '404040', 0, 5),
( 'Red blur', 'footerHeight', '', '30', 0, 5),
( 'Red blur', 'footerColor', '', '3D3D3D', 0, 5),
( 'Red blur', 'mediaDefaultAutoplay', '', '1', 0, 5),
( 'Red blur', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 5),
( 'Red blur', 'mediaShowDuration', '', '5', 0, 5),
( 'Red blur', 'videoDefaultVolume', '', '80', 0, 5),
( 'Red blur', 'videoAutoplay', '', '0', 0, 5),
( 'Red blur', 'mediaBgColor', '', '000000', 0, 5),
( 'Red blur', 'mediaCtrlsBgColor', '', '363D40', 0, 5),
( 'Red blur', 'mediaCtrlsBgAlpha', '', '80', 0, 5),
( 'Red blur', 'mediaCtrlsColor', '', 'D3DADE', 0, 5),
( 'Red blur', 'mediaCtrlsAlpha', '', '100', 0, 5),



( 'Dodger Blue', 'startWithMonday', '', '1', 0, 6),
( 'Dodger Blue', 'dateFormat', '', '%d-%m-%y %t', 0, 6),
( 'Dodger Blue', 'dateFormatShort', '', '%t', 0, 6),
( 'Dodger Blue', 'time', '', '0', 0, 6),
( 'Dodger Blue', 'appMaxWidth', '', '600', 0, 6),
( 'Dodger Blue', 'appMaxHeight', '', '550', 0, 6),
( 'Dodger Blue', 'appMinWidth', '', '360', 0, 6),
( 'Dodger Blue', 'appMinHeight', '', '420', 0, 6),
( 'Dodger Blue', 'startViewSize', '', 'viewSizeMax', 0, 6),
( 'Dodger Blue', 'startViewState', '', 'viewStateDays', 0, 6),
( 'Dodger Blue', 'bgColors', '', 'EDEDED;4196E9', 0, 6),
( 'Dodger Blue', 'bgCornerRadius', '', '6', 0, 6),
( 'Dodger Blue', 'strokeColor', '', '000000', 0, 6),
( 'Dodger Blue', 'headerHeight', '', '100', 0, 6),
( 'Dodger Blue', 'headerPadding', '', '20', 0, 8),
( 'Dodger Blue', 'headerBgColors', '', '4196E9;6782AD', 0, 6),
( 'Dodger Blue', 'headerBgStrokeColor', '', '203540', 0, 6),
( 'Dodger Blue', 'headerContentColor', '', 'FFFFFF', 0, 6),
( 'Dodger Blue', 'headerContentStrokeColor', '', '404040', 0, 6),
( 'Dodger Blue', 'headerFontSize', '', '40', 0, 6),
( 'Dodger Blue', 'daysNamesColor', '', '000000', 0, 6),
( 'Dodger Blue', 'daysNamesFontSize', '', '24', 0, 6),
( 'Dodger Blue', 'datesBgColors', '', 'E2EDF7;C6D0D9', 0, 6),
( 'Dodger Blue', 'priority0Color', '', '55FF00', 0, 6),
( 'Dodger Blue', 'priority1Color', '', '55FF00', 0, 6),
( 'Dodger Blue', 'priority2Color', '', 'FFD400', 0, 6),
( 'Dodger Blue', 'priority3Color', '', '3E90E0', 0, 6),
( 'Dodger Blue', 'dateFontSize', '', '40', 0, 6),
( 'Dodger Blue', 'dateColor', '', '050505', 0, 6),
( 'Dodger Blue', 'dateStrokeColor', '', '050505', 0, 6),
( 'Dodger Blue', 'showDateEventsCount', '', '1', 0, 6),
( 'Dodger Blue', 'dateEventsCountFontSize', '', '12', 0, 6),
( 'Dodger Blue', 'dateEventsCountColor', '', 'FFFFFF', 0, 6),
( 'Dodger Blue', 'eventsListHeaderHeight', '', '50', 0, 6),
( 'Dodger Blue', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 6),
( 'Dodger Blue', 'eventsListHeaderColor', '', '404040', 0, 6),
( 'Dodger Blue', 'eventsListHeaderFontSize', '', '20', 0, 6),
( 'Dodger Blue', 'eventHeaderHeight', '', '40', 0, 6),
( 'Dodger Blue', 'eventHeaderFontSize', '', '20', 0, 6),
( 'Dodger Blue', 'eventHeaderColor', '', '000000', 0, 6),
( 'Dodger Blue', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 6),
( 'Dodger Blue', 'eventContentDatesFontSize', '', '18', 0, 6),
( 'Dodger Blue', 'eventContentDatesColor', '', '808080', 0, 6),
( 'Dodger Blue', 'eventContentDescriptionFontSize', '', '16', 0, 6),
( 'Dodger Blue', 'eventContentDescriptionColor', '', '404040', 0, 6),
( 'Dodger Blue', 'footerHeight', '', '30', 0, 6),
( 'Dodger Blue', 'footerColor', '', 'D6D6D6', 0, 6),
( 'Dodger Blue', 'mediaDefaultAutoplay', '', '1', 0, 6),
( 'Dodger Blue', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 6),
( 'Dodger Blue', 'mediaShowDuration', '', '5', 0, 6),
( 'Dodger Blue', 'videoDefaultVolume', '', '80', 0, 6),
( 'Dodger Blue', 'videoAutoplay', '', '0', 0, 6),
( 'Dodger Blue', 'mediaBgColor', '', '000000', 0, 6),
( 'Dodger Blue', 'mediaCtrlsBgColor', '', '363D40', 0, 6),
( 'Dodger Blue', 'mediaCtrlsBgAlpha', '', '80', 0, 6),
( 'Dodger Blue', 'mediaCtrlsColor', '', 'D3DADE', 0, 6),
( 'Dodger Blue', 'mediaCtrlsAlpha', '', '100', 0, 6),




( 'Indian Red', 'startWithMonday', '', '1', 0, 7),
( 'Indian Red', 'dateFormat', '', '%d-%m-%y %t', 0, 7),
( 'Indian Red', 'dateFormatShort', '', '%t', 0, 7),
( 'Indian Red', 'time', '', '1', 0, 7),
( 'Indian Red', 'appMaxWidth', '', '600', 0, 7),
( 'Indian Red', 'appMaxHeight', '', '550', 0, 7),
( 'Indian Red', 'appMinWidth', '', '360', 0, 7),
( 'Indian Red', 'appMinHeight', '', '420', 0, 7),
( 'Indian Red', 'startViewSize', '', 'viewSizeMax', 0, 7),
( 'Indian Red', 'startViewState', '', 'viewStateDays', 0, 7),
( 'Indian Red', 'bgColors', '', 'FFEFA3;5D2117', 0, 7),
( 'Indian Red', 'bgCornerRadius', '', '6', 0, 7),
( 'Indian Red', 'strokeColor', '', '808080', 0, 7),
( 'Indian Red', 'headerHeight', '', '100', 0, 7),
( 'Indian Red', 'headerPadding', '', '20', 0, 7),
( 'Indian Red', 'headerBgColors', '', '7E3F30;9C4E3B', 0, 7),
( 'Indian Red', 'headerBgStrokeColor', '', '203540', 0, 7),
( 'Indian Red', 'headerContentColor', '', 'FFFFFF', 0, 7),
( 'Indian Red', 'headerContentStrokeColor', '', '404040', 0, 7),
( 'Indian Red', 'headerFontSize', '', '40', 0, 7),
( 'Indian Red', 'daysNamesColor', '', '000000', 0, 7),
( 'Indian Red', 'daysNamesFontSize', '', '20', 0, 7),
( 'Indian Red', 'datesBgColors', '', '7E3F30;7E3F30', 0, 7),
( 'Indian Red', 'priority0Color', '', 'FFFFFF', 0, 9),
( 'Indian Red', 'priority1Color', '', 'FFE8B9', 0, 7),
( 'Indian Red', 'priority2Color', '', 'FFD400', 0, 7),
( 'Indian Red', 'priority3Color', '', 'FF0000', 0, 7),
( 'Indian Red', 'dateFontSize', '', '40', 0, 7),
( 'Indian Red', 'dateColor', '', 'FBEDBE', 0, 7),
( 'Indian Red', 'dateStrokeColor', '', '404040', 0, 7),
( 'Indian Red', 'showDateEventsCount', '', '1', 0, 7),
( 'Indian Red', 'dateEventsCountFontSize', '', '12', 0, 7),
( 'Indian Red', 'dateEventsCountColor', '', '606060', 0, 7),
( 'Indian Red', 'eventsListHeaderHeight', '', '50', 0, 7),
( 'Indian Red', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 7),
( 'Indian Red', 'eventsListHeaderColor', '', '404040', 0, 7),
( 'Indian Red', 'eventsListHeaderFontSize', '', '20', 0, 7),
( 'Indian Red', 'eventHeaderHeight', '', '40', 0, 7),
( 'Indian Red', 'eventHeaderFontSize', '', '20', 0, 7),
( 'Indian Red', 'eventHeaderColor', '', '000000', 0, 7),
( 'Indian Red', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 7),
( 'Indian Red', 'eventContentDatesFontSize', '', '18', 0, 7),
( 'Indian Red', 'eventContentDatesColor', '', '808080', 0, 7),
( 'Indian Red', 'eventContentDescriptionFontSize', '', '16', 0, 7),
( 'Indian Red', 'eventContentDescriptionColor', '', '404040', 0, 7),
( 'Indian Red', 'footerHeight', '', '30', 0, 7),
( 'Indian Red', 'footerColor', '', '808080', 0, 7),
( 'Indian Red', 'mediaDefaultAutoplay', '', '1', 0, 7),
( 'Indian Red', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 7),
( 'Indian Red', 'mediaShowDuration', '', '5', 0, 7),
( 'Indian Red', 'videoDefaultVolume', '', '80', 0, 7),
( 'Indian Red', 'videoAutoplay', '', '0', 0, 7),
( 'Indian Red', 'mediaBgColor', '', '000000', 0, 7),
( 'Indian Red', 'mediaCtrlsBgColor', '', '363D40', 0, 7),
( 'Indian Red', 'mediaCtrlsBgAlpha', '', '80', 0, 7),
( 'Indian Red', 'mediaCtrlsColor', '', 'D3DADE', 0, 7),
( 'Indian Red', 'mediaCtrlsAlpha', '', '100', 0, 7),



( 'Sky blue', 'startWithMonday', '', '1', 0, 8),
( 'Sky blue', 'dateFormat', '', '%d-%m-%y %t', 0, 8),
( 'Sky blue', 'dateFormatShort', '', '%t', 0, 8),
( 'Sky blue', 'time', '', '0', 0, 8),
( 'Sky blue', 'appMaxWidth', '', '600', 0, 8),
( 'Sky blue', 'appMaxHeight', '', '550', 0, 8),
( 'Sky blue', 'appMinWidth', '', '360', 0, 8),
( 'Sky blue', 'appMinHeight', '', '420', 0, 8),
( 'Sky blue', 'startViewSize', '', 'viewSizeMax', 0, 8),
( 'Sky blue', 'startViewState', '', 'viewStateDays', 0, 8),
( 'Sky blue', 'bgColors', '', 'FFFFFF;FFFFFF', 0, 8),
( 'Sky blue', 'bgCornerRadius', '', '8', 0, 8),
( 'Sky blue', 'strokeColor', '', '808080', 0, 8),
( 'Sky blue', 'headerHeight', '', '100', 0, 8),
( 'Sky blue', 'headerPadding', '', '0', 0, 8),
( 'Sky blue', 'headerBgColors', '', '37BEFE;37BEFE', 0, 8),
( 'Sky blue', 'headerBgStrokeColor', '', '203540', 0, 8),
( 'Sky blue', 'headerContentColor', '', 'FFFFFF', 0, 8),
( 'Sky blue', 'headerContentStrokeColor', '', '404040', 0, 8),
( 'Sky blue', 'headerFontSize', '', '40', 0, 8),
( 'Sky blue', 'daysNamesColor', '', '17506B', 0, 8),
( 'Sky blue', 'daysNamesFontSize', '', '20', 0, 8),
( 'Sky blue', 'datesBgColors', '', 'FFFFFF;FFFFFF', 0, 8),
( 'Sky blue', 'priority0Color', '', '55FF00', 0, 8),
( 'Sky blue', 'priority1Color', '', '55FF00', 0, 8),
( 'Sky blue', 'priority2Color', '', 'FFD400', 0, 8),
( 'Sky blue', 'priority3Color', '', 'FF0000', 0, 8),
( 'Sky blue', 'dateFontSize', '', '33', 0, 8),
( 'Sky blue', 'dateColor', '', '404040', 0, 8),
( 'Sky blue', 'dateStrokeColor', '', '404040', 0, 8),
( 'Sky blue', 'showDateEventsCount', '', '1', 0, 8),
( 'Sky blue', 'dateEventsCountFontSize', '', '12', 0, 8),
( 'Sky blue', 'dateEventsCountColor', '', '606060', 0, 8),
( 'Sky blue', 'eventsListHeaderHeight', '', '50', 0, 8),
( 'Sky blue', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 8),
( 'Sky blue', 'eventsListHeaderColor', '', '404040', 0, 8),
( 'Sky blue', 'eventsListHeaderFontSize', '', '20', 0, 8),
( 'Sky blue', 'eventHeaderHeight', '', '40', 0, 8),
( 'Sky blue', 'eventHeaderFontSize', '', '20', 0, 8),
( 'Sky blue', 'eventHeaderColor', '', '000000', 0, 8),
( 'Sky blue', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 8),
( 'Sky blue', 'eventContentDatesFontSize', '', '18', 0, 8),
( 'Sky blue', 'eventContentDatesColor', '', '808080', 0, 8),
( 'Sky blue', 'eventContentDescriptionFontSize', '', '16', 0, 8),
( 'Sky blue', 'eventContentDescriptionColor', '', '404040', 0, 8),
( 'Sky blue', 'footerHeight', '', '30', 0, 8),
( 'Sky blue', 'footerColor', '', '2FA4DB', 0, 8),
( 'Sky blue', 'mediaDefaultAutoplay', '', '1', 0, 8),
( 'Sky blue', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 8),
( 'Sky blue', 'mediaShowDuration', '', '5', 0, 8),
( 'Sky blue', 'videoDefaultVolume', '', '80', 0, 8),
( 'Sky blue', 'videoAutoplay', '', '0', 0, 8),
( 'Sky blue', 'mediaBgColor', '', '000000', 0, 8),
( 'Sky blue', 'mediaCtrlsBgColor', '', '363D40', 0, 8),
( 'Sky blue', 'mediaCtrlsBgAlpha', '', '80', 0, 8),
( 'Sky blue', 'mediaCtrlsColor', '', 'D3DADE', 0, 8),
( 'Sky blue', 'mediaCtrlsAlpha', '', '100', 0, 8),



( 'Midnight blue', 'startWithMonday', '', '1', 0, 9),
( 'Midnight blue', 'dateFormat', '', '%d-%m-%y %t', 0, 9),
( 'Midnight blue', 'dateFormatShort', '', '%t', 0, 9),
( 'Midnight blue', 'time', '', '0', 0, 9),
( 'Midnight blue', 'appMaxWidth', '', '600', 0, 9),
( 'Midnight blue', 'appMaxHeight', '', '550', 0, 9),
( 'Midnight blue', 'appMinWidth', '', '360', 0, 9),
( 'Midnight blue', 'appMinHeight', '', '420', 0, 9),
( 'Midnight blue', 'startViewSize', '', 'viewSizeMax', 0, 9),
( 'Midnight blue', 'startViewState', '', 'viewStateDays', 0, 9),
( 'Midnight blue', 'bgColors', '', 'FFFFFF;FFFFFF', 0, 9),
( 'Midnight blue', 'bgCornerRadius', '', '15', 0, 9),
( 'Midnight blue', 'strokeColor', '', '808080', 0, 9),
( 'Midnight blue', 'headerHeight', '', '100', 0, 9),
( 'Midnight blue', 'headerPadding', '', '20', 0, 9),
( 'Midnight blue', 'headerBgColors', '', '025F9C;025F9C', 0, 9),
( 'Midnight blue', 'headerBgStrokeColor', '', '203540', 0, 9),
( 'Midnight blue', 'headerContentColor', '', 'FFFFFF', 0, 9),
( 'Midnight blue', 'headerContentStrokeColor', '', '404040', 0, 9),
( 'Midnight blue', 'headerFontSize', '', '40', 0, 9),
( 'Midnight blue', 'daysNamesColor', '', '025287', 0, 9),
( 'Midnight blue', 'daysNamesFontSize', '', '20', 0, 9),
( 'Midnight blue', 'datesBgColors', '', 'CFEBFF;AFDDFF', 0, 9),
( 'Midnight blue', 'priority0Color', '', '55FF00', 0, 9),
( 'Midnight blue', 'priority1Color', '', '55FF00', 0, 9),
( 'Midnight blue', 'priority2Color', '', 'FFD400', 0, 9),
( 'Midnight blue', 'priority3Color', '', 'FF0000', 0, 9),
( 'Midnight blue', 'dateFontSize', '', '33', 0, 9),
( 'Midnight blue', 'dateColor', '', '404040', 0, 9),
( 'Midnight blue', 'dateStrokeColor', '', '404040', 0, 9),
( 'Midnight blue', 'showDateEventsCount', '', '1', 0, 9),
( 'Midnight blue', 'dateEventsCountFontSize', '', '12', 0, 9),
( 'Midnight blue', 'dateEventsCountColor', '', '606060', 0, 9),
( 'Midnight blue', 'eventsListHeaderHeight', '', '50', 0, 9),
( 'Midnight blue', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 9),
( 'Midnight blue', 'eventsListHeaderColor', '', '404040', 0, 9),
( 'Midnight blue', 'eventsListHeaderFontSize', '', '20', 0, 9),
( 'Midnight blue', 'eventHeaderHeight', '', '40', 0, 9),
( 'Midnight blue', 'eventHeaderFontSize', '', '20', 0, 9),
( 'Midnight blue', 'eventHeaderColor', '', '000000', 0, 9),
( 'Midnight blue', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 9),
( 'Midnight blue', 'eventContentDatesFontSize', '', '18', 0, 9),
( 'Midnight blue', 'eventContentDatesColor', '', '808080', 0, 9),
( 'Midnight blue', 'eventContentDescriptionFontSize', '', '16', 0, 9),
( 'Midnight blue', 'eventContentDescriptionColor', '', '404040', 0, 9),
( 'Midnight blue', 'footerHeight', '', '30', 0, 9),
( 'Midnight blue', 'footerColor', '', '025F9C', 0, 9),
( 'Midnight blue', 'mediaDefaultAutoplay', '', '1', 0, 9),
( 'Midnight blue', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 9),
( 'Midnight blue', 'mediaShowDuration', '', '5', 0, 9),
( 'Midnight blue', 'videoDefaultVolume', '', '80', 0, 9),
( 'Midnight blue', 'videoAutoplay', '', '0', 0, 9),
( 'Midnight blue', 'mediaBgColor', '', '000000', 0, 9),
( 'Midnight blue', 'mediaCtrlsBgColor', '', '363D40', 0, 9),
( 'Midnight blue', 'mediaCtrlsBgAlpha', '', '80', 0, 9),
( 'Midnight blue', 'mediaCtrlsColor', '', 'D3DADE', 0, 9),
( 'Midnight blue', 'mediaCtrlsAlpha', '', '100', 0, 9),



( 'Baby blue', 'startWithMonday', '', '1', 0, 10),
( 'Baby blue', 'dateFormat', '', '%d-%m-%y %t', 0, 10),
( 'Baby blue', 'dateFormatShort', '', '%t', 0, 10),
( 'Baby blue', 'time', '', '0', 0, 10),
( 'Baby blue', 'appMaxWidth', '', '600', 0, 10),
( 'Baby blue', 'appMaxHeight', '', '550', 0, 10),
( 'Baby blue', 'appMinWidth', '', '360', 0, 10),
( 'Baby blue', 'appMinHeight', '', '420', 0, 10),
( 'Baby blue', 'startViewSize', '', 'viewSizeMax', 0, 10),
( 'Baby blue', 'startViewState', '', 'viewStateDays', 0, 10),
( 'Baby blue', 'bgColors', '', '84CFEE;499BD5', 0, 10),
( 'Baby blue', 'bgCornerRadius', '', '15', 0, 10),
( 'Baby blue', 'strokeColor', '', '808080', 0, 10),
( 'Baby blue', 'headerHeight', '', '100', 0, 10),
( 'Baby blue', 'headerPadding', '', '0', 0, 10),
( 'Baby blue', 'headerBgColors', '', '4CA0DE;7FCDF3', 0, 10),
( 'Baby blue', 'headerBgStrokeColor', '', '4CA0DE', 0, 10),
( 'Baby blue', 'headerContentColor', '', 'FFFFFF', 0, 10),
( 'Baby blue', 'headerContentStrokeColor', '', '404040', 0, 10),
( 'Baby blue', 'headerFontSize', '', '40', 0, 10),
( 'Baby blue', 'daysNamesColor', '', 'FFFFFF', 0, 10),
( 'Baby blue', 'daysNamesFontSize', '', '24', 0, 10),
( 'Baby blue', 'datesBgColors', '', '9EC8E0;9EC8E0', 0, 10),
( 'Baby blue', 'priority0Color', '', '55FF00', 0, 10),
( 'Baby blue', 'priority1Color', '', '55FF00', 0, 10),
( 'Baby blue', 'priority2Color', '', 'FFD400', 0, 10),
( 'Baby blue', 'priority3Color', '', 'FF0000', 0, 10),
( 'Baby blue', 'dateFontSize', '', '40', 0, 10),
( 'Baby blue', 'dateColor', '', 'FFFFFF', 0, 10),
( 'Baby blue', 'dateStrokeColor', '', '404040', 0, 10),
( 'Baby blue', 'showDateEventsCount', '', '1', 0, 10),
( 'Baby blue', 'dateEventsCountFontSize', '', '12', 0, 10),
( 'Baby blue', 'dateEventsCountColor', '', '606060', 0, 10),
( 'Baby blue', 'eventsListHeaderHeight', '', '50', 0, 10),
( 'Baby blue', 'eventsListHeaderbgColors', '', 'F3F3F3;E6E6E6', 0, 10),
( 'Baby blue', 'eventsListHeaderColor', '', '404040', 0, 10),
( 'Baby blue', 'eventsListHeaderFontSize', '', '20', 0, 10),
( 'Baby blue', 'eventHeaderHeight', '', '40', 0, 10),
( 'Baby blue', 'eventHeaderFontSize', '', '20', 0, 10),
( 'Baby blue', 'eventHeaderColor', '', '000000', 0, 10),
( 'Baby blue', 'eventContentBgColors', '', 'F3F3F3;E6E6E6', 0, 10),
( 'Baby blue', 'eventContentDatesFontSize', '', '18', 0, 10),
( 'Baby blue', 'eventContentDatesColor', '', '808080', 0, 10),
( 'Baby blue', 'eventContentDescriptionFontSize', '', '16', 0, 10),
( 'Baby blue', 'eventContentDescriptionColor', '', '404040', 0, 10),
( 'Baby blue', 'footerHeight', '', '30', 0, 10),
( 'Baby blue', 'footerColor', '', 'D1D1D1', 0, 10),
( 'Baby blue', 'mediaDefaultAutoplay', '', '1', 0, 10),
( 'Baby blue', 'mediaScaleType', '', 'scaleTypeTouchFromOutside', 0, 10),
( 'Baby blue', 'mediaShowDuration', '', '5', 0, 10),
( 'Baby blue', 'videoDefaultVolume', '', '80', 0, 10),
( 'Baby blue', 'videoAutoplay', '', '0', 0, 10),
( 'Baby blue', 'mediaBgColor', '', '000000', 0, 10),
( 'Baby blue', 'mediaCtrlsBgColor', '', '363D40', 0, 10),
( 'Baby blue', 'mediaCtrlsBgAlpha', '', '80', 0, 10),
( 'Baby blue', 'mediaCtrlsColor', '', 'D3DADE', 0, 10),
( 'Baby blue', 'mediaCtrlsAlpha', '', '100', 0, 10)	";
?>